---
- name: Is {{ rpmfusion_free_repo_name }} already installed
  stat:
    path: "{{ rpmfusion_free_repo_file }}"
  register: rpmfusion_free_repo_file_exists

- name: Install {{ rpmfusion_free_repo_name }} repo file
  yum:
    name: "{{ rpmfusion_free_repo_url }}"
    state: present
  when: not rpmfusion_free_repo_file_exists.stat.exists
  notify:
    - yum update cache

- name: Install {{ rpmfusion_free_repo_name }} GPG key.
  rpm_key:
    key: "{{ rpmfusion_free_repo_gpg_key_url }}"
    state: present
  when: not rpmfusion_free_repo_file_exists.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - yum update cache

- name: Disable {{ rpmfusion_free_repo_name }} repo.
  ini_file:
    path: "{{ rpmfusion_free_repo_file }}"
    section: rpmfusion-free-updates
    option: enabled
    value: "0"
  notify:
    - yum update cache
  when: rpmfusion_free_repo_disabled|bool

- name: Remove  {{ rpmfusion_free_repo_name }}
  yum:
    name: "rpmfusion-free*"
    state: absent
  notify:
    - yum update cache
  when: rpmfusion_free_repo_remove|bool